name: deploy-to-github-pages
on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  gh-pages-deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v2

      - name: Setup node env
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17.0'

      - name: Install dependencies
        run: npm install

      - name: Generate
        env:
          NODE_ENV: production
        run: npm run generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist